spring:
  application:
    name: service-score
  zipkin:
    baseUrl: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9091/eureka/,http://127.0.0.1:9092/eureka/,http://127.0.0.1:9093/eureka/
feign:
  hystrix:
    enabled: true