spring:
  application:
    name: eureka-server
eureka:
  server:
    # 禁用自我保护模式
    # 默认情况下，如果Eureka Server在一定时间内没有接收到某个微服务实例的心跳，Eureka Server将会注销该实例（默认90秒）。
    # 但是当网络分区故障发生时，微服务与Eureka Server之间无法正常通信，以上行为可能变得非常危险了——因为微服务本身其实是健康的，此时本不应该注销这个微服务。
    enableSelfPreservation: false
  instance:
    preferIpAddress: true
    hostname: 127.0.0.1
  client:
    # 多个节点的eureka-server以下两项都是false
    fetchRegistry: true
    registerWithEureka: true
