server:
  port: 6060
spring:
  application:
    name: service-order
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9091/eureka/,http://127.0.0.1:9092/eureka/,http://127.0.0.1:9093/eureka/