spring:
  application:
    name: service-order
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9091/eureka/,http://127.0.0.1:9092/eureka/,http://127.0.0.1:9093/eureka/
# feign集成的hystrix需要手动开启
feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 2000
management:
  endpoint:
    hystrix:
      stream:
        enabled: true